# SOPS configuration for encrypting secrets
# Generate age key: age-keygen -o ~/.config/sops/age/keys.txt
# Encrypt file: sops config/secrets.enc.yaml
# Decrypt file: sops -d config/secrets.enc.yaml

creation_rules:
  - path_regex: \.enc\.yaml$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    # Replace the above age public key with your actual public key from age-keygen
    # The private key stays in ~/.config/sops/age/keys.txt (never commit this)
